[package]
name = "accel-derive"
version = "0.3.0-alpha.1"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

description   = "Procedual macro for writing GPGPU kernel"
documentation = "https://docs.rs/accel-derive/"
repository    = "https://github.com/termoshtt/accel"
keywords      = ["GPGPU", "CUDA", "proc-macro"]
license       = "MIT"
readme        = "README.md"
categories    = []

[lib]
proc-macro = true

[dependencies]
failure = "0.1.6"
proc-macro2 = "1.0.7"
quote = "1.0.2"
toml = "0.5.5"
serde = { version = "1.0.104", features = ["derive"] }
maplit = "1.0.2"
dirs = "2.0.2"

[dependencies.syn]
version = "1.0.13"
features = ["full", "extra-traits"]

[dev-dependencies]
accel = { path = "../accel" }
trybuild = "1.0.19"
