[package]
name = "accel-derive"
version = "0.2.1-alpha.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

description   = "Procedual macro for writing GPGPU kernel"
documentation = "https://docs.rs/accel-derive/"
repository    = "https://github.com/termoshtt/accel"
keywords      = ["GPGPU", "CUDA", "proc-macro"]
license       = "MIT"
readme        = "README.md"
categories    = []

[lib]
proc-macro = true

[dependencies]
failure = "0.1"
proc-macro2 = "1.0"
quote = "1.0"
nvptx = "0.2.2"

[dependencies.syn]
version = "1.0"
features = ["full", "extra-traits"]
