[package]
name = "accel-derive"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description   = "Procedual macro for writing GPGPU kernel"
documentation = "https://docs.rs/accel-derive/"
repository    = "https://github.com/termoshtt/accel"
keywords      = ["GPGPU", "CUDA", "proc-macro"]
license       = "MIT"
readme        = "README.md"
categories    = []

[lib]
proc-macro = true

[dependencies]
synom = "0.11.3"
quote = "0.4"
toml = "0.4.5"
tempdir = "0.3"
glob = "0.2.11"
procedurals = "0.2"
serde = "1.0"
serde_derive = "1.0"
derive_more = "0.10"

[dependencies.syn]
version = "0.12"
features = ["full", "fold", "parsing", "printing", "extra-traits"]
default-features = false
