image: rust:1.40

stages:
  - test

cache:
  paths:
    - target/
    - cargo/
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

check:
  stage: test
  script:
    - cargo check

derive:
  image: registry.gitlab.com/rust-cuda/container/ubuntu18.04-cuda10.2:master
  stage: test
  script:
    - cd accel-derive
    - cargo test
