image: rust:1.40

stages:
  - docker
  - test

cache:
  paths:
    - target/
    - cargo/
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

check:
  stage: test
  before_script:
    - rustup toolchain add nightly-2020-01-02 --profile minimal
    - rustup target add nvptx64-nvidia-cuda --toolchain nightly-2020-01-02
  script:
    - cd $CI_PROJECT_DIR/accel; cargo check
    - cd $CI_PROJECT_DIR/accel-core; cargo check
    - cd $CI_PROJECT_DIR/accel-derive; cargo check

derive:
  image: registry.gitlab.com/rust-cuda/container/ubuntu18.04-cuda10.2:master
  stage: test
  script:
    - cd accel-derive
    - cargo test

.build:
  image: docker:stable
  stage: docker
  services:
    - docker:dind
  before_script:
    - apk add make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make -C docker ${TAG}
  only:
    - master
    - tags

include: '/docker/ci.yml'
