stages:
  - build
  - test

cargo-check:
  stage: build
  image: "registry.gitlab.com/termoshtt/rust-cuda"
  script:
    - cargo check
    - cd accel-core/ && cargo check && cd -
    - cd accel-derive/ && cargo check && cd -
    - cd cuda-sys/ && cargo check && cd -

cargo-run-gpu:
  stage: test
  image: "registry.gitlab.com/termoshtt/rust-cuda"
  script:
    - cd accel-example && cargo run -v --example add
  tags:
    - nvidia-docker
