
cargo-build:
  image: rust
  script:
    - cargo build -v
  tags:
    - docker

cargo-run-gpu:
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - nvidia-docker run --rm -u "$UID:100" -v $PWD:/source --env-file=.nvidia-docker.env registry.gitlab.com/termoshtt/rust-cuda cargo run --example add
  tags:
    - nvidia-docker
