
cargo-build:
  image: rust
  script:
    - cargo build -v
  tags:
    - docker

cargo-test:
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - nvidia-docker run --rm -u "$UID:100" -v $PWD:/source -e "RUSTUP_TOOLCHAIN=nightly" -e "HOME=/root" registry.gitlab.com/termoshtt/rust-cuda cargo test -v
  tags:
    - nvidia-docker
