image: rust:1.40

stages:
  - docker
  - test

cache:
  paths:
    - target/
    - cargo/
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

check:
  stage: test
  script:
    - cargo check

derive:
  image: registry.gitlab.com/rust-cuda/container/ubuntu18.04-cuda10.2:master
  stage: test
  script:
    - cd accel-derive
    - cargo test

.build:
  image: docker:stable
  stage: docker
  services:
    - docker:dind
  before_script:
    - apk add make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make ${TAG}
  only:
    changes:
      - docker/*

include: '/docker/ci.yml'
