
cargo-check:
  image: "registry.gitlab.com/termoshtt/rust-cuda"
  script:
    - cargo check
    - cd accel-core/ && cargo check && cd -
    - cd accel-derive/ && cargo check && cd -
    - cd cuda-sys/ && cargo check && cd -

cargo-run-gpu:
  image: "registry.gitlab.com/termoshtt/rust-cuda"
  script:
    - cargo run -v --example add
  tags:
    - nvidia-docker
