image: registry.gitlab.com/termoshtt/accel/ubuntu18.04-cuda10.2:master

stages:
  - docker
  - test

cache:
  paths:
    - target/
    - cargo/
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo-check:
  stage: test
  script:
    - cd $CI_PROJECT_DIR/accel; cargo check
    - cd $CI_PROJECT_DIR/accel-core; cargo check
    - cd $CI_PROJECT_DIR/accel-derive; cargo check

test:accel-derive:
  stage: test
  script:
    - cd accel-derive
    - cargo test

test:accel:
  stage: test
  script:
    - ldconfig -p | grep -E 'nvidia|cuda'
    - cd accel
    - cargo test
  tags:
    - gpu

.build:
  image: docker:stable
  stage: docker
  services:
    - docker:dind
  before_script:
    - apk add make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make -C docker ${TAG}
  only:
    - master
    - tags

include: '/docker/ci.yml'
