language: rust
sudo: false
dist: trusty

rust:
  - nightly

script:
  - cargo install cargo-check
  - cargo check
  - cd accel-core/ && cargo check && cd -
  - cd accel-derive/ && cargo check && cd -

env:
  - RUST_BACKTRACE=1
