[package]
name = "acc"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
glob = "*"

[dependencies.futures-await-syn]
version = "*"
features = ["full", "fold", "parsing", "printing", "extra-traits"]
default-features = false

[dev-dependencies]
acc-derive = { path = "./acc-derive" }
