[package]
name = "acc"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
glob = "*"

[dependencies.cuda-sys]
version = "0.1.0"
path = "./cuda-sys"

[dev-dependencies.acc-derive]
version = "0.1.0"
path = "./acc-derive"
