version: 2

jobs:
  build:
    docker:
      - image: termoshtt/rust-cuda
    steps:
      - checkout
      - run:
          name: Check format
          command: |
            cargo fmt --all -- --write-mode=diff
      - run:
          name: Check cuda-sys
          command: |
            cd cuda-sys
            cargo check
      - run:
          name: check accel-derive
          command: |
            cd accel-derive
            cargo check
      - run:
          name: test nvptx
          command: |
            cd nvptx
            cargo test -v
      - run:
          name: build PTX of accel-core
          command: |
            cd nvptx
            cargo install -f
            cd ../accel-core
            cargo nvptx
      - run:
          name: Check accel
          command: |
            cargo check -v --example add