version: 2
jobs:
  check_format:
    docker:
      - image: registry.gitlab.com/termoshtt/rust-cuda:cuda9.1
    steps:
      - checkout
      - run: cargo fmt --all -- --write-mode=diff

  check_cuda_sys:
    docker:
      - image: registry.gitlab.com/termoshtt/rust-cuda:cuda9.1
    steps:
      - checkout
      - run:
          name: Check cuda-sys
          command: |
            cd cuda-sys
            cargo check

  check_derive:
    docker:
      - image: registry.gitlab.com/termoshtt/rust-cuda:cuda9.1
    steps:
      - checkout
      - run:
          name: check accel-derive
          command: |
            cd accel-derive
            cargo check

  build_core:
    docker:
      - image: registry.gitlab.com/termoshtt/rust-cuda:cuda9.1
    steps:
      - checkout
      - run:
          name: build PTX of accel-core
          command: |
            cargo install nvptx -f
            cd ../accel-core
            cargo nvptx

  build_example_add:
    docker:
      - image: registry.gitlab.com/termoshtt/rust-cuda:cuda9.1
    steps:
      - checkout
      - run:
          name: Check accel
          command: |
            cargo check -v --example add

workflows:
  version: 2
  tests:
    jobs:
      - check_format
      - check_derive
      - build_core
      - build_example_add
