version: 2

jobs:
  build:
    docker:
      - image: termoshtt/rust-cuda
    steps:
      - checkout
      - run:
          name: Check format
          command: |
            cargo fmt --all -- --write-mode=diff
      - run:
          name: Check cuda-sys
          command: |
            cd cuda-sys
            cargo check
      - run:
          name: Check accel-derive
          command: |
            cd accel-derive
            cargo test -v
      - run:
          name: Check accel-core
          command: |
            cd accel-core
            cargo check
      - run:
          name: Check accel
          command: |
            cargo check -v --example add
