[package]
name = "accel-example"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies.accel]
path = ".."
version = "0.1.0"

[dependencies.accel-derive]
path = "../accel-derive"
version = "0.1.0"

