name: "CUDA without GPU"
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  centos7-cuda10_2:
    runs-on: ubuntu-latest
    name: CentOS 7, CUDA 10.2
    steps:
    - uses: actions/checkout@v1
    - name: cargo test
      id: test
      uses: termoshtt/rust-cuda-docker-action@centos7-cuda10_2
      with:
        path: accel-derive

  ubuntu1804-cuda10_2:
    runs-on: ubuntu-latest
    name: Ubuntu 18.04, CUDA 10.2
    steps:
    - uses: actions/checkout@v1
    - name: cargo test
      id: test
      uses: termoshtt/rust-cuda-docker-action@ubuntu1804-cuda10_2
      with:
        path: accel-derive
